---

- name: nginx installed
  yum: name=nginx state=latest

- name: nginx enabled
  service: name=nginx enabled=yes

- name: selinux configued
  seboolean: name=httpd_setrlimit state=yes persistent=yes

- name: html configured
  copy:
    dest: /usr/share/nginx/html/index.html
    content: '<html><head><title>tf-puppet-nginx</title></head><body><h1>Hello, World</h1></body></html>'
  notify: nginx restarted
